# Generated by Django 4.2 on 2023-05-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('monitor_time', models.DateTimeField()),
                ('monitor_star', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
