# Generated by Django 4.2 on 2023-05-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordata',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
