# Generated by Django 4.2 on 2023-05-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_lateststatus_user_id_alter_rundata_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundata',
            name='run_clock',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitdata',
            name='sit_clock',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkdata',
            name='walk_clock',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rundata',
            name='now_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sitdata',
            name='now_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sportsinfo',
            name='now_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sportsinfo',
            name='sports_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='walkdata',
            name='now_time',
            field=models.DateField(),
        ),
    ]
