# Generated by Django 4.2 on 2023-05-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=20)),
                ('user_passwd', models.CharField(default=None, max_length=20)),
                ('user_phone', models.CharField(default=None, max_length=11)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
